import { ContentLanguageItemDto } from "~/lib/api/types";
import { useTranslations } from "~/contexts/TranslationsProvider";
import { formatDurationHuman } from "~/lib/utils/general";

interface ContentTableProps {
  items: ContentLanguageItemDto[];
  showVideoCount?: boolean;
  /** Array of matching language codes to filter by (includes aliases) */
  matchingLanguageCodes?: string[] | null;
}

interface LanguageDisplay {
  languageCode: string;
  languageName: string;
  count: number;
  autoGeneratedCount: number;
}

/**
 * Format count display showing human-verified and auto-generated breakdown
 * Examples: "(3 verified)" if all human, "(2 verified & 1 auto-generated)" if mixed, "(3 auto-generated)" if all auto
 */
function formatCountDisplay(lang: LanguageDisplay): string {
  const humanCount = lang.count - lang.autoGeneratedCount;
  if (lang.autoGeneratedCount === 0) {
    return `(${lang.count} verified)`;
  }
  if (humanCount === 0) {
    return `(${lang.autoGeneratedCount} auto-generated)`;
  }
  return `(${humanCount} verified & ${lang.autoGeneratedCount} auto-generated)`;
}

/**
 * Filter and format languages based on selection
 * - If no language selected: show all as codes (EN, FR, etc.)
 * - If language selected: show only matching languages with full name
 */
function formatLanguages(
  languages: LanguageDisplay[],
  matchingCodes: string[] | null | undefined
): JSX.Element {
  const hasFilter = matchingCodes && matchingCodes.length > 0;

  // Filter to matching languages if codes are provided
  const displayLanguages = hasFilter
    ? languages.filter((lang) => {
        const codesSet = new Set(matchingCodes.map((c) => c.toLowerCase()));
        return codesSet.has(lang.languageCode.toLowerCase());
      })
    : languages;

  return (
    <span>
      {displayLanguages.map((lang, idx) => {
        const hasAutoGenerated = lang.autoGeneratedCount > 0;
        return (
          <span key={lang.languageCode}>
            <span className={hasAutoGenerated ? 'text-gold-light' : ''}>
              {/* Show full name when filtered, code otherwise */}
              {hasFilter ? lang.languageName : lang.languageCode.toUpperCase()}
              {' '}{formatCountDisplay(lang)}
            </span>
            {idx < displayLanguages.length - 1 && ', '}
          </span>
        );
      })}
      {displayLanguages.length === 0 && <span className="text-white/50">—</span>}
    </span>
  );
}

export function ContentTable({
  items,
  showVideoCount = true,
  matchingLanguageCodes,
}: ContentTableProps) {
  const { strings } = useTranslations();

  if (items.length === 0) {
    return (
      <p className="body-b3 text-white/50 py-16">No content available</p>
    );
  }

  return (
    <>
      {/* Desktop: Traditional table */}
      <div className="hidden tablet:block overflow-x-auto">
        <table className="w-full text-left">
          <thead>
            <tr className="border-b border-white/10">
              <th className="pb-12 text-white/50 body-b4 uppercase font-600">
                {strings.content_availability_title_column}
              </th>
              {showVideoCount && (
                <th className="pb-12 text-white/50 body-b4 uppercase font-600 text-center whitespace-nowrap">
                  Videos / Duration
                </th>
              )}
              <th className="pb-12 text-white/50 body-b4 uppercase font-600">
                {strings.content_availability_audio}
              </th>
              <th className="pb-12 text-white/50 body-b4 uppercase font-600">
                {strings.content_availability_subtitles}
              </th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr
                key={item.contentId}
                className="border-b border-white/5 hover:bg-white/5 transition-colors"
              >
                <td className="py-12 pr-16">
                  <span className="body-b3 text-white">{item.title}</span>
                </td>
                {showVideoCount && (
                  <td className="py-12 text-center whitespace-nowrap">
                    <span className="body-b3 text-white/70">
                      {item.videoCount} ({formatDurationHuman(item.durationSeconds)})
                    </span>
                  </td>
                )}
                <td className="py-12 pr-16">
                  <span className="body-b3 text-white">
                    {formatLanguages(item.audioLanguages, matchingLanguageCodes)}
                  </span>
                </td>
                <td className="py-12">
                  <span className="body-b3 text-white">
                    {formatLanguages(item.subtitleLanguages, matchingLanguageCodes)}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Mobile: Stacked cards */}
      <div className="tablet:hidden space-y-12">
        {items.map((item) => (
          <div key={item.contentId} className="bg-white/5 p-16 rounded-md">
            {/* Title and video count */}
            <div className="mb-12">
              <h4 className="body-b2 text-white font-600">{item.title}</h4>
              {showVideoCount && (
                <p className="body-b4 text-white/50 mt-4">
                  {item.videoCount} videos ({formatDurationHuman(item.durationSeconds)})
                </p>
              )}
            </div>

            {/* Languages */}
            <div className="space-y-8">
              <div className="body-b3">
                <span className="text-white/50">{strings.content_availability_audio}: </span>
                <span className="text-white">
                  {formatLanguages(item.audioLanguages, matchingLanguageCodes)}
                </span>
              </div>
              <div className="body-b3">
                <span className="text-white/50">{strings.content_availability_subtitles}: </span>
                <span className="text-white">
                  {formatLanguages(item.subtitleLanguages, matchingLanguageCodes)}
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
