import { LanguageAvailabilityDto, LanguageInfoDto } from "~/lib/api/types";
import { useTranslations } from "~/contexts/TranslationsProvider";

interface LanguageSummaryProps {
  audioLanguages: LanguageAvailabilityDto[] | LanguageInfoDto[];
  subtitleLanguages: LanguageAvailabilityDto[] | LanguageInfoDto[];
  layout: 'columns' | 'inline';
  maxVisible?: number;
  /** Array of matching language codes to filter by (includes aliases) */
  matchingLanguageCodes?: string[] | null;
}

// Note: Both LanguageAvailabilityDto and LanguageInfoDto now have count and autoGeneratedCount fields
type LanguageDto = LanguageAvailabilityDto | LanguageInfoDto;

/**
 * Check if a language has any auto-generated content
 */
function hasAutoGenerated(lang: LanguageDto): boolean {
  return lang.autoGeneratedCount > 0;
}

/**
 * Format count display showing human-verified and auto-generated breakdown
 * Examples: "(3 verified)" if all human, "(2 verified & 1 auto-generated)" if mixed, "(3 auto-generated)" if all auto
 */
function formatCountDisplay(lang: LanguageDto): string {
  const humanCount = lang.count - lang.autoGeneratedCount;
  if (lang.autoGeneratedCount === 0) {
    return `(${lang.count} verified)`;
  }
  if (humanCount === 0) {
    return `(${lang.autoGeneratedCount} auto-generated)`;
  }
  return `(${humanCount} verified & ${lang.autoGeneratedCount} auto-generated)`;
}

function formatLanguageName(lang: LanguageDto): string {
  return `${lang.languageName} ${formatCountDisplay(lang)}`;
}

/**
 * Filter languages by matching language codes
 * If no codes are provided, return all languages
 */
function filterLanguages<T extends { languageCode: string }>(
  languages: T[],
  matchingCodes: string[] | null | undefined
): T[] {
  if (!matchingCodes || matchingCodes.length === 0) return languages;
  const codesSet = new Set(matchingCodes.map((c) => c.toLowerCase()));
  return languages.filter((lang) => codesSet.has(lang.languageCode.toLowerCase()));
}

export function LanguageSummary({
  audioLanguages,
  subtitleLanguages,
  layout,
  maxVisible = 5,
  matchingLanguageCodes,
}: LanguageSummaryProps) {
  const { strings } = useTranslations();
  const hasFilter = matchingLanguageCodes && matchingLanguageCodes.length > 0;

  // Filter languages if codes are selected
  const filteredAudio = filterLanguages(audioLanguages, matchingLanguageCodes);
  const filteredSubtitles = filterLanguages(subtitleLanguages, matchingLanguageCodes);

  if (layout === 'columns') {
    const visibleAudio = filteredAudio.slice(0, hasFilter ? filteredAudio.length : maxVisible);
    const remainingAudio = hasFilter ? 0 : Math.max(0, filteredAudio.length - maxVisible);
    const visibleSubtitles = filteredSubtitles.slice(0, hasFilter ? filteredSubtitles.length : maxVisible);
    const remainingSubtitles = hasFilter ? 0 : Math.max(0, filteredSubtitles.length - maxVisible);

    return (
      <div className="grid grid-cols-2 gap-24">
        {/* Audio column */}
        <div>
          <h4 className="body-b4 uppercase text-white/50 mb-8">
            {strings.content_availability_audio}
          </h4>
          <ul className="space-y-4">
            {visibleAudio.map((lang) => {
              const isAuto = hasAutoGenerated(lang);
              return (
                <li key={lang.languageCode} className="body-b3 text-white">
                  <span className={isAuto ? 'text-gold-light' : ''}>
                    {lang.languageName} {formatCountDisplay(lang)}
                  </span>
                </li>
              );
            })}
            {remainingAudio > 0 && (
              <li className="body-b3 text-white/70">
                {strings.content_availability_more_languages.replace('{count}', String(remainingAudio))}
              </li>
            )}
            {filteredAudio.length === 0 && (
              <li className="body-b3 text-white/50">—</li>
            )}
          </ul>
        </div>

        {/* Subtitles column */}
        <div>
          <h4 className="body-b4 uppercase text-white/50 mb-8">
            {strings.content_availability_subtitles}
          </h4>
          <ul className="space-y-4">
            {visibleSubtitles.map((lang) => {
              const isAuto = hasAutoGenerated(lang);
              return (
                <li key={lang.languageCode} className="body-b3 text-white">
                  <span className={isAuto ? 'text-gold-light' : ''}>
                    {lang.languageName} {formatCountDisplay(lang)}
                  </span>
                </li>
              );
            })}
            {remainingSubtitles > 0 && (
              <li className="body-b3 text-white/70">
                {strings.content_availability_more_languages.replace('{count}', String(remainingSubtitles))}
              </li>
            )}
            {filteredSubtitles.length === 0 && (
              <li className="body-b3 text-white/50">—</li>
            )}
          </ul>
        </div>
      </div>
    );
  }

  // Inline layout for PPV summary
  const visibleAudio = filteredAudio.slice(0, hasFilter ? filteredAudio.length : maxVisible);
  const remainingAudio = hasFilter ? 0 : Math.max(0, filteredAudio.length - maxVisible);
  const visibleSubtitles = filteredSubtitles.slice(0, hasFilter ? filteredSubtitles.length : maxVisible);
  const remainingSubtitles = hasFilter ? 0 : Math.max(0, filteredSubtitles.length - maxVisible);

  return (
    <div className="space-y-8">
      {/* Audio line */}
      <div className="body-b3">
        <span className="text-white/70">{strings.content_availability_audio}: </span>
        <span className="text-white">
          {visibleAudio.map((lang, idx) => {
            const isAuto = hasAutoGenerated(lang);
            return (
              <span key={lang.languageCode}>
                <span className={isAuto ? 'text-gold-light' : ''}>
                  {formatLanguageName(lang)}
                </span>
                {idx < visibleAudio.length - 1 && ', '}
              </span>
            );
          })}
          {remainingAudio > 0 && (
            <span className="text-white/70">
              , {strings.content_availability_more_languages.replace('{count}', String(remainingAudio))}
            </span>
          )}
          {filteredAudio.length === 0 && <span className="text-white/50">—</span>}
        </span>
      </div>

      {/* Subtitles line */}
      <div className="body-b3">
        <span className="text-white/70">{strings.content_availability_subtitles}: </span>
        <span className="text-white">
          {visibleSubtitles.map((lang, idx) => {
            const isAuto = hasAutoGenerated(lang);
            return (
              <span key={lang.languageCode}>
                <span className={isAuto ? 'text-gold-light' : ''}>
                  {/* Show full name when filtered, code otherwise */}
                  {hasFilter ? lang.languageName : lang.languageCode.toUpperCase()}
                  {' '}{formatCountDisplay(lang)}
                </span>
                {idx < visibleSubtitles.length - 1 && ', '}
              </span>
            );
          })}
          {remainingSubtitles > 0 && (
            <span className="text-white/70">
              , {strings.content_availability_more_languages.replace('{count}', String(remainingSubtitles))}
            </span>
          )}
          {filteredSubtitles.length === 0 && <span className="text-white/50">—</span>}
        </span>
      </div>
    </div>
  );
}
