/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  safelist: ["text-gold", "text-red", "btn", "btn--red", "btn--blue", "btn--secondary", "btn--gold"],
  theme: {
    borderRadius: {
      'none': '0',
      'sm': '0.375rem',
      'md': '0.5rem',
      'lg': '.75rem',
      'xl': '1rem',
      '2xl': '1.5rem',
      'full': '9999px',
    },
    screens: {
      tablet: "40rem",
      desktop: "64rem",
      wide: "80rem",
    },
    colors: {
      transparent: "transparent",
      brand: "rgb(var(--brand))",
      "brand-light": "rgb(var(--brand-light))",
      "brand-lighter": "rgb(var(--brand-lighter))",
      "brand-dark": "rgb(var(--brand-dark))",
      gold: "rgb(var(--gold))",
      "gold-light": "rgb(var(--gold-light))",
      grey: "rgb(var(--grey))",
      "grey-light": "rgb(var(--grey-light))",
      "grey-dark": "rgb(var(--grey-dark))",
      "grey-grey": "rgb(var(--grey-grey))",
      white: "rgb(var(--white))",
      black: "rgb(var(--black))",
      red: "rgb(var(--red))",
      link: "rgb(var(--link))",
      purple: "rgb(var(--purple))",
      "purple-dark": "rgb(var(--purple-dark))",
      orange: "rgb(var(--orange))",
      "neutral-blue": "rgb(var(--neutral-blue))",
      "text-muted": "rgb(var(--text-muted))",
      "text-placeholder": "rgb(var(--text-placeholder))",
      "overlay-dark": "rgb(var(--overlay-dark))"
    },
    fontFamily: {
      "avenir-next": [
        "Avenir Next",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "sans-serif",
      ],
      figtree: [
        "Figtree",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "sans-serif",
      ],
      "display-serif": ["Bauer Bodoni Std", "Georgia", "serif"],
    },
    fontWeight: {
      200: "200",
      300: "300",
      400: "400",
      500: "500",
      600: "600",
      700: "700",
      800: "800",
      900: "900",
    },
    fontSize: {
      10: "10px",
      12: "12px",
      14: "14px",
      16: "16px",
      18: "18px",
      20: "20px",
      24: "24px",
      32: "32px",
      40: "40px",
      48: "48px",
      xxs: "10px",
      xs: "12px",
      sm: "14px",
      md: "16px",
      lg: "18px",
      xl: "20px",
      "2xl": "24px",
      "3xl": "32px",
    },
    spacing: {
      0: "0",
      1: "0.0625rem",
      2: "0.125rem",
      4: "0.25rem",
      8: "0.5rem",
      10: "0.625rem",
      12: "0.75rem",
      14: "0.875rem",
      16: "1rem",
      20: "1.25rem",
      24: "1.5rem",
      28: "1.75rem",
      32: "2rem",
      36: "2.25rem",
      40: "2.5rem",
      48: "3rem",
      56: "3.5rem",
      60: "3.75rem",
      64: "4rem",
      80: "5rem",
      96: "6rem",
      120: "7.5rem",
      128: "8rem",

      xxs: "0.5rem",
      xs: "0.75rem",
      sm: "1rem",
      md: "1.5rem",
      lg: "2rem",
      xl: "2.5rem",
      "2xl": "3rem",
      "3xl": "4rem",

      "sp-0.5": "0.25rem",
      "sp-1": "0.5rem",
      "sp-1.5": "0.75rem",
      "sp-2": "1rem",
      "sp-3": "1.5rem",
      "sp-4": "2rem",
      "sp-5": "3rem",
      "sp-6": "4rem",
      "sp-7": "5rem",
      "sp-8": "6rem",
      "sp-9": "8rem",
    },
    lineHeight: {
      "8": "8px",
      "14": "14px",
      "16": "16px",
      "18": "18px",
      "20": "20px",
      "24": "24px",
      "32": "32px",
      "40": "40px",
      "48": "48px",
      "56": "56px",
    },
    letterSpacing: {
      "tighter": "-.05em",
      "normal": "normal",
      "wide": ".03em",
      "wider": "1em",
    },
    boxShadow: {
      'none': 'none',
      'card': '0px 4px 14px 0px rgba(12, 22, 47, 0.3)',
      'card-hover': '0px 8px 32px 0px rgba(0, 0, 0, 0.4)',
      'dropdown': '0px 4px 16px 0px rgba(0, 0, 0, 0.25)',
    },
    extend: {
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fade-in 1s ease-in',
      },
    },
  },
  plugins: [
    function({ addUtilities }) {
      addUtilities({
        '.scrollbar-hide': {
          '-ms-overflow-style': 'none',
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': {
            display: 'none',
          },
        },
        '.icon-sm': { width: '0.75rem', height: '0.75rem' },
        '.icon-md': { width: '1rem', height: '1rem' },
        '.icon-lg': { width: '1.5rem', height: '1.5rem' },
        '.icon-xl': { width: '2rem', height: '2rem' },
        '.icon-2xl': { width: '2.5rem', height: '2.5rem' },
        '.gradient-brand': {
          background: 'linear-gradient(265.3deg, rgba(22, 37, 76, 0) 40%, #051237 60%), linear-gradient(0deg, #051337 0%, rgba(5, 19, 55, 0.6) 100%)',
        },
        '.gradient-purple': {
          background: 'linear-gradient(180deg, #5745FF 0%, #231F92 100%)',
        },
        '.gradient-purple-dark': {
          background: 'linear-gradient(180deg, #242099 0%, #0C0B33 100%)',
        },
      });
    },
  ],
};
